# Source: https://github.com/catppuccin/atuin/tree/abfab12de743aa73cf20ac3fa61e450c4d96380c
[theme]
name = "catppuccin-mocha-green"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#fab387"
AlertError = "#f38ba8"
Annotation = "#a6e3a1"
Base = "#cdd6f4"
Guidance = "#9399b2"
Important = "#f38ba8"
Title = "#a6e3a1"
